# GET http://localhost:8080/api/users

# POST  http://localhost:8080/api/users/login

# Content-Type: application/json

# {
#     user:
# }

POST  http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "ross",
    "email": "ros1ss@",
    "password": "1234"
}

###

POST  http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "test1@mail.ru",
    "password": "1234"
}

### 
GET   http://localhost:8080/api/user
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiJ9.ewogIGlzQWRtaW46IGZhbHNlLAogIGlzQWN0aXZlOiB0cnVlLAogIF9pZDogNjBiOGEzYTZlODU2YjMxZmYwZmIwNDUzLAogIGVtYWlsOiAncm9zczExMTExMTExQG1haWwucnUnLAogIG5hbWU6ICdyb3NzJywKICBwYXNzd29yZDogJyQyYSQxMCQ4R1JsTEx3dDBPREFQQVN2TU1RN2xlVlpXYTltVGNTY2dETjRqc3EybklZVWp2Sk9FSzlQRycKfQ.YHhqLIqaxTDGy-r4JKiSG-dmjmX34dPRzkYgm6imdmE"
}
###
Get  http://localhost:8080/api/products/6074568952b7892bb84ca10b
Content-Type: application/json

###
Post  http://localhost:8080/api/products
Content-Type: application/json

{
  "name": "Marinara",
  "image": "files/img",
  "price": "14.88",
  "description": "pizza with seafood",
  "enabled": []
}