export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const UPDATE_CART = 'UPDATE_CART'

export const FETCH_CART_PRODUCTS_REQUEST = 'FETCH_CART_PRODUCTS_REQUEST'
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS'
export const FETCH_CART_PRODUCTS_FAILURE = 'FETCH_CART_PRODUCTS_FAILURE'

export const TOGGLE_CART = 'TOGGLE_CART'
