export const UPDATE_CART = 'UPDATE_CART'
export const UPDATE_CART_ID = 'UPDATE_CART_ID'

export const FETCH_CART_PRODUCTS_REQUEST = 'FETCH_CART_PRODUCTS_REQUEST'
export const FETCH_CART_PRODUCTS_SUCCESS = 'FETCH_CART_PRODUCTS_SUCCESS'
export const FETCH_CART_PRODUCTS_FAILURE = 'FETCH_CART_PRODUCTS_FAILURE'

export const TOGGLE_CART = 'TOGGLE_CART'
